# Generated by Django 4.0.4 on 2022-05-25 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_bookinstance_borrower_alter_bookinstance_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='statuse',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o ', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book Availablity', max_length=2),
        ),
    ]
